### ISSUE TITLE
[Feature Request] Files not restored in correct order and groups

### ISSUE THREAD

**Issue by lonix1** [iulian-radu-at/save-restore-editors#1]
Thanks for this nice extension!

Some issues:
- The files are not saved in the correct order (so they open in a random order)
- The files are not saved according to the editor group they were in (so they all open in one group)

Are these vscode limitations, or could the extension support those features?

**Comment by iulianraduat** [comment]
Hi @lonix1,

Unfortunately the VS Code API provides access only to:
* the list of all visible text editors (one per group)
* the list of all text documents (a text document can be displayed in multiple text editors)

So for the moment we cannot get all the text documents opened in all groups. Hence your feature request must be postponed.

Cheers,
Iulian

**Comment by lonix1** [comment]
> the list of all visible text editors (one per group)

So is it possible to save documents per group? So even if they open randomly, they will at least open in a separate group. Sorry if I'm misunderstanding.

**Comment by iulianraduat** [comment]
I can only get the visible editor per each group. So if you have 3 text editors in a group, I can only save the visible one and the others two are lost :(

**Comment by lonix1** [comment]
Ok I understand. It's unfortunate vscode doesn't have this API functionality!

I hope we can talk about this again in the future. Until then the extension is as good as it can be... thanks!

**Comment by lonix1** [comment]
@iulian-radu-at  Does the new tabs API help?

**Comment by iulianraduat** [comment]
@lonix1 you can try the version 1.2.0 and let me know your opinion 😃 

It is not perfect as the current API (1.67.0) only provides tab groups describing in which viewColumn is a file but without the possibility to open non-documents files at restore time nor specify the arrangement of viewColumns in a grid nor provide a call to find how many viewColumns exists in the window or make an editor active. The API for vscode.window still has a lot to evolve 😞 

What is your opinion: if there are already opened documents in tab groups, should the restore tab groups be merged in the current tab groups or they should add new tab groups? The maximum number of viewColumns supported by the API is 9 😵

Thanks

**Comment by lonix1** [comment]
I'm not sure what "viewColumns" represents, so maybe my opinion is not relevant here. But if I understand correctly, the issue is:
- tabs groups exist, and they contain tabs
- user clicks to restore old tabs saved via this extension

Interesting question. I think it should be the same as what is done by browsers. I think they will open new windows with the saved tabs.
