### ISSUE TITLE
Allow saving over a group that already exists

### ISSUE THREAD

**Issue by seancolsen** [iulian-radu-at/save-restore-editors#2]
## Current behavior

Here's what my workflow looks like:

![Peek 2022-05-25 14-34](https://user-images.githubusercontent.com/42411/170341834-f2fbec5d-1834-4581-9979-6f12bb2ef5b9.gif)

1. I'm on a feature branch, doing some work. 

1. I need to switch to another branch to chase down a higher-priority issue.

1. Before I switch branches, I'd like to save all my open editors using the name of my current git branch as the name of the saved editor set.

1. I use the "Save all open text editors" action, and supply my git branch name.

1. But uh-oh! I already have a saved editor set with that name. I need to cancel, then go delete that group, then go back to save again. It's a pain especially because I don't always remember whether or not I've saved the editors in my current branch.

## Desired behavior

1. Allow the user to enter a name for the set, even if that name already exists.

    (Further, while entering a name, it would be nice if existing saved editor sets appeared as options to select, but that's just extra and not actually necessary to address the real problem.)

1. If the name already exists, provide an additional menu allowing the user to choose between "Update saved editor set" and "Cancel".

**Comment by iulianraduat** [comment]
Hi @seancolsen,

In version 1.3.0 I added a setting which allows to overwrite an existing saved group having the same name.
There is also a setting which let you specify if you should be asked for confirmation when you do this.

I hope that this solution will resolve you problem.

Cheers,
Iulian

**Comment by seancolsen** [comment]
@iulian-radu-at  Works great! I just needed to tweak my settings. Thanks!
