### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Hydrock** [iulian-radu-at/save-restore-editors#4]
Hi. I can not understand how to use this extension. Can you add Usage section into Readme file?

**Comment by LukeDickerson19** [comment]
+1

It seems we need to open the command pallet (Ctrl + Shift + P), and then type "Save and restore editors" to view/run the commands this extension provides.

**Comment by iulianraduat** [comment]
Hi @Hydrock and @LukeDickerson19,

I added more usage information in 1.5.1.
Please take a look and let me know if it still needs to be improved.

Cheers,
Iulian

**Comment by LukeDickerson19** [comment]
perfect! lgtm
